### ISSUE TITLE
New feature found. Game Music Emulator.

### ISSUE THREAD

**Issue by itsdarklikehell** [zshall/tvs-video-game-engine#3]
[Game Music Emu](https://docs.libretro.com/library/game_music_emu/#game-music-emu)

[Background](https://docs.libretro.com/library/game_music_emu/#background)
Multi-purpose video game console music player.

[Author/License](https://docs.libretro.com/library/game_music_emu/#authorlicense)
The Game Music Emu core has been authored by

Blargg
The Game Music Emu core is licensed under

[GPLv3](https://github.com/libretro/libretro-gme/blob/master/LICENSE)
A summary of the licenses behind RetroArch and its cores can be found [here](https://docs.libretro.com/development/licenses/).

[Extensions](https://docs.libretro.com/library/game_music_emu/#extensions)
Content that can be loaded by the Game Music Emu core have the following file extensions:

```
.ay
.gbs
.gym
.hes
.kss
.nsf
.nsfe
.sap
.spc
.vgm
.vgz
```
[Features](https://docs.libretro.com/library/game_music_emu/#features)
Frontend-level settings or features that the Game Music Emu core respects.

Too bad it cant play *.mod file but i think that can allso be acomplished with a diffrent core but here is an example:
```
  - number: -9
    abbr: GME
    title: Currently Playing - (kirby/1.spc).
    name: Gameboy Advance Emulator Channel.
    description: An example of a Gameboy Advance emulator on a LINE-IN (EMULATOR Provided to you by nostalgist.github.io, ROM Provided to you by sgtstroopwafel.hopto.org)
    video-game:
      game: "../roms/music/kirby/1.spc"
      console: gme
```
